name: chemos_test
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0=py36_1003
  - bleach=1.5.0=py36_0
  - bzip2=1.0.6=1
  - cffi=1.11.5=py36h5e8e0c9_1
  - chardet=3.0.4=py36_1003
  - cryptography-vectors=2.3.1=py36_1000
  - cycler=0.10.0=py_1
  - html5lib=0.9999999=py36_0
  - idna=2.8=py36_1000
  - kiwisolver=1.0.1=py36h2d50403_2
  - libprotobuf=3.6.1=hd28b015_0
  - markdown=2.6.11=py_0
  - matplotlib=3.0.2=py36_1
  - matplotlib-base=3.0.2=py36hb2d221d_1
  - mkl_fft=1.0.10=py36_0
  - mkl_random=1.0.2=py36_0
  - nltk=3.2.4=py36_0
  - pip=18.1=py36_1000
  - protobuf=3.6.1=py36hfc679d8_1
  - pycparser=2.19=py_0
  - pyopenssl=18.0.0=py36_1000
  - pyparsing=2.3.0=py_0
  - pysocks=1.6.8=py36_1002
  - python-dateutil=2.7.5=py_0
  - pytz=2018.7=py_0
  - requests=2.21.0=py36_1000
  - setuptools=40.6.3=py36_0
  - six=1.12.0=py36_1000
  - slackclient=1.2.1=py_0
  - sqlalchemy=1.2.15=py36h470a237_0
  - tensorboard=0.4.0rc3=py36_2
  - tensorflow=1.4.0=py36_0
  - tornado=5.1.1=py36h470a237_0
  - urllib3=1.24.1=py36_1000
  - webencodings=0.5.1=py_1
  - websocket-client=0.54.0=py36_1000
  - werkzeug=0.14.1=py_0
  - wheel=0.32.3=py36_0
  - blas=1.0=mkl
  - ca-certificates=2018.03.07=0
  - certifi=2018.11.29=py36_0
  - click=7.0=py36_0
  - cryptography=2.4.1=py36ha12b0ac_0
  - cython=0.29=py36h0a44026_0
  - flask=1.0.2=py36_1
  - freetype=2.9.1=hb4e5f40_0
  - intel-openmp=2019.1=144
  - itsdangerous=1.1.0=py36_0
  - jinja2=2.10=py36_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libpng=1.6.35=ha441bb4_0
  - markupsafe=1.1.0=py36h1de35cc_0
  - mkl=2018.0.3=1
  - ncurses=6.1=h0a44026_1
  - numpy=1.15.4=py36h6a91979_0
  - numpy-base=1.15.4=py36h8a80b8c_0
  - openssl=1.1.1a=h1de35cc_0
  - python=3.6.7=haf84260_0
  - readline=7.0=h1de35cc_5
  - scipy=1.1.0=py36h28f7352_1
  - sqlite=3.25.3=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - argh==0.26.2
    - lazyme==0.0.20
    - pathtools==0.1.2
    - pillow==5.3.0
    - pyyaml==3.13
    - tensorflow-tensorboard==0.4.0rc3
    - tflearn==0.3.2
    - watchdog==0.9.0
prefix: /anaconda3/envs/chemos_test
